In [1]:
import numpy as np

# COMPUTE STABILITY - INCOMPLETE

In [2]:
condensed_tree = np.array([
    (10, 11, 0.49307512, 5), (10, 12, 0.49307512, 5), (11,  0, 1.30856724, 1),
    (11,  8, 1.30856724, 1), (11,  1, 1.30856724, 1), (11,  6, 1.30856724, 1),
    (11,  9, 1.30856724, 1), (12,  2, 1.62536102, 1), (12,  5, 1.62536102, 1),
    (12,  3, 1.62536102, 1), (12,  7, 1.62536102, 1), (12,  4, 1.62536102, 1)])
condensed_tree

array([[10.        , 11.        ,  0.49307512,  5.        ],
       [10.        , 12.        ,  0.49307512,  5.        ],
       [11.        ,  0.        ,  1.30856724,  1.        ],
       [11.        ,  8.        ,  1.30856724,  1.        ],
       [11.        ,  1.        ,  1.30856724,  1.        ],
       [11.        ,  6.        ,  1.30856724,  1.        ],
       [11.        ,  9.        ,  1.30856724,  1.        ],
       [12.        ,  2.        ,  1.62536102,  1.        ],
       [12.        ,  5.        ,  1.62536102,  1.        ],
       [12.        ,  3.        ,  1.62536102,  1.        ],
       [12.        ,  7.        ,  1.62536102,  1.        ],
       [12.        ,  4.        ,  1.62536102,  1.        ]])

In [3]:
largest_child = condensed_tree[:,1].max()
# largest_child = condensed_tree['child'].max()
smallest_cluster = condensed_tree[:,0].min()
# smallest_cluster = condensed_tree['parent'].min()

num_clusters = (condensed_tree[:,0].max() - smallest_cluster + 1)


In [4]:
if largest_child < smallest_cluster:
    largest_child = smallest_cluster

In [5]:
sorted_child_data = np.sort(condensed_tree[:,[1,2]],
                            axis=0)
sorted_children = sorted_child_data[:,0].copy()
sorted_lambdas = sorted_child_data[:,1].copy()
births_arr = np.nan * np.ones(int(largest_child) + 1)
births = births_arr.copy()
# births_arr = np.nan * np.ones(int(largest_child) + 1)
# births = (<np.double_t *> births_arr.data)
# sorted_children = sorted_child_data['child'].copy()
# sorted_lambdas = sorted_child_data['lambda_val'].copy()

In [6]:
parents = condensed_tree[:,0]
sizes = condensed_tree[:,3]
lambdas = condensed_tree[:,2]

# parents = condensed_tree['parent']
# sizes = condensed_tree['child_size']
# lambdas = condensed_tree['lambda_val']

In [7]:
current_child = -1
min_lambda = 0

In [8]:
for row in range(sorted_child_data.shape[0]):
    child = sorted_children[row]
    lambda_ = sorted_lambdas[row]

    if child == current_child:
        min_lambda = min(min_lambda, lambda_)
    elif current_child != -1:
        births[int(current_child)] = min_lambda
        current_child = child
        min_lambda = lambda_
    else:
        # Initialize
        current_child = child
        min_lambda = lambda_
if current_child != -1:
    births[int(current_child)] = min_lambda
births[int(smallest_cluster)] = 0.0

In [9]:
#logic for choosing stable clusters
result_arr = np.zeros(int(num_clusters))


for i in range(condensed_tree.shape[0]):
    parent = parents[i]
    lambda_ = lambdas[i]
    child_size = sizes[i]
    result_index = parent - smallest_cluster

    result_arr[int(result_index)] += (lambda_ - births[int(parent)]) * child_size


In [10]:
result_pre_dict = np.vstack((np.arange((smallest_cluster),
                                        condensed_tree[:,0].max() + 1),
                                result_arr)).T


In [11]:
result_pre_dict

array([[10.       ,  4.9307512],
       [11.       , -1.5839689],
       [12.       ,  0.       ]])

In [12]:
result_arr

array([ 4.9307512, -1.5839689,  0.       ])